### ISSUE TITLE
No Android / Smart device Support??

### ISSUE THREAD

**Issue by Julluhub92** [Johnaconda/Johnacondas-Custom-Lanista-Css#2]
Hey!
Maybe the wrong place to post, if so excuse my ignorance. 
As the title reads, is there no support for Android and other Smart devices? 
Appreciate the assistance and time! 🥴🙂

Also great work on the skin, I love the look!! 👍🏼

**Comment by Johnaconda** [comment]
Hi there! no sorry im not aware of any android support for this, you might be able to install firefox and the addons for that using it that way but i will not work on it atleast :).
